language: scala
scala:
  - 2.10.2
script: 'cd oppgaver && ./sbt "test-only scalakurs.basics.* scalakurs.functional.* scalakurs.for_comprehensions.* scalakurs.collections.* scalakurs.oop.* scalakurs.patternmatching.* scalakurs.option.* scalakurs.either.* scalakurs.typevariance.* scalakurs.myfutures.*"'